// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3y-Df2SqMsNAm2hxWzenMzmh1oqjI4y4',
    appId: '1:915378347171:web:14741a7eb689de1007b316',
    messagingSenderId: '915378347171',
    projectId: 'doctorpert-a8e29',
    authDomain: 'doctorpert-a8e29.firebaseapp.com',
    storageBucket: 'doctorpert-a8e29.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSuvySqAYlo9LNEsOXdRxQefxJEqwsMzk',
    appId: '1:915378347171:android:d49ee3f2a3554ad207b316',
    messagingSenderId: '915378347171',
    projectId: 'doctorpert-a8e29',
    storageBucket: 'doctorpert-a8e29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE5Dyp06ER1Ync3Ie57v6Ndl3BRxqbXHg',
    appId: '1:915378347171:ios:79a9189e4495148607b316',
    messagingSenderId: '915378347171',
    projectId: 'doctorpert-a8e29',
    storageBucket: 'doctorpert-a8e29.appspot.com',
    iosClientId: '915378347171-6l3o5tb9jh7ns7sgij0aqsqemogdomu2.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorPert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE5Dyp06ER1Ync3Ie57v6Ndl3BRxqbXHg',
    appId: '1:915378347171:ios:79a9189e4495148607b316',
    messagingSenderId: '915378347171',
    projectId: 'doctorpert-a8e29',
    storageBucket: 'doctorpert-a8e29.appspot.com',
    iosClientId: '915378347171-6l3o5tb9jh7ns7sgij0aqsqemogdomu2.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorPert',
  );
}
